### ISSUE TITLE
include with dot in string

### ISSUE THREAD

**Issue by aisk** [Thriftpy/thriftpy2#121]
animal.people.thrift:

```thift
struct People {
       1: i32 age,
       2: string name,
}
```

test.thrift:

```thrift
include "animal.people.thrift"

typedef animal.people.People People
```

main.py:

```python
import thriftpy2


thriftpy2.load('./test.thrift')
```

---

Run it:

```
$ python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    thriftpy2.load('./test.thrift')
  File "/Users/asaka/Codes/thriftpy2/thriftpy2/parser/__init__.py", line 33, in load
    include_dir=include_dir)
  File "/Users/asaka/Codes/thriftpy2/thriftpy2/parser/parser.py", line 588, in parse
    parser.parse(data)
  File "/Users/asaka/Codes/thriftpy2/venv/lib/python3.7/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/asaka/Codes/thriftpy2/venv/lib/python3.7/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/Users/asaka/Codes/thriftpy2/thriftpy2/parser/parser.py", line 399, in p_ref_type
    (p[1], p.lineno(1)))
thriftpy2.parser.exc.ThriftParserError: No type found: 'people.People', at line 3
```

The original thrift can parse this style's thrift but thriftpy2 does not. I think this should be a bug in thriftpy2.

**Comment by aisk** [comment]
WIthout typedef, using the `People` type like `animal.people.People` or `People` have the same issue.

**Comment by aisk** [comment]
Took a dig on this, found there may be some confilct if we have a `a.b.thrift` or two file called `a.thrift` / `b.thrift` and have a include in them. But the origin thrift do implemented this.

**Comment by ethe** [comment]
Yes, I think we should fix it.
