### ISSUE TITLE
当返回对象是一个map<SkuPairKey, DefectQueryResDto>时，接口解析失败

### ISSUE THREAD

**Issue by taomin1** [Thriftpy/thriftpy2#135]
开发的接口定义如下：
public ResultDto<Map<SkuPairKey, DefectQueryResDto>> batchGetInventoryDefectSku4MultiWareHouse(
           List<DefectQueryReqDto> queryDtos) throws TException

报错信息如下：
Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/caixia/PycharmProjects/newPythonProject/b2b_api_case_core/monitor_tools/case_listener.py", line 24, in __deco
    func(*args, **kwargs)
  File "/Users/caixia/PycharmProjects/newPythonProject/b2b_api_inventory_case_suite/testcase/test_inventory_thrift/test_query/test_TDefectQueryService/test_batchGetInventoryDefectSku.py", line 29, in test_batchGetInventoryDefectSku
    res = self.client.batchGetInventoryDefectSku(**kwargs["request"])
  File "/Users/caixia/PycharmProjects/newPythonProject/b2b_api_case_center/wizard/thrift_api/inventory_api/TDefectQueryService.py", line 22, in batchGetInventoryDefectSku
    return self.thriftclientfactory.call("batchGetInventoryDefectSku", params_dict)
  File "/Users/caixia/PycharmProjects/newPythonProject/b2b_api_case_core/object/tool/thriftClientFactoryV2.py", line 90, in call
    res = fun(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/thrift.py", line 203, in _req
    return self._recv(_api)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/thrift.py", line 222, in _recv
    result.read(self._iprot)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/thrift.py", line 150, in read
    iprot.read_struct(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/protocol/binary.py", line 386, in read_struct
    return read_struct(self.trans, obj, self.decode_response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/protocol/binary.py", line 315, in read_struct
    read_val(inbuf, f_type, f_container_spec, decode_response))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/protocol/binary.py", line 288, in read_val
    read_struct(inbuf, obj, decode_response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/protocol/binary.py", line 315, in read_struct
    read_val(inbuf, f_type, f_container_spec, decode_response))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/protocol/binary.py", line 282, in read_val
    result[k_val] = v_val
TypeError: unhashable type: 'SkuPairKey'

**Comment by ethe** [comment]
There is a reason: `TypeError: unhashable type: 'SkuPairKey'`, it is not hashable so it is not able to be a map key.

**Comment by taomin1** [comment]
But，The code of the R&D engineer defines hashCode

public class SkuPairKey extends BaseThritDto {

    @FieldDoc(description = "仓库id", requiredness = Requiredness.REQUIRED)
    private long wareHouseId; // 仓库ID

    @FieldDoc(description = "skuCode", requiredness = Requiredness.REQUIRED)
    private int skuCode; // sku编码

    public SkuPairKey() {
        super();
    }

    public SkuPairKey(long wareHouseId, int skuCode) {
        this.wareHouseId = wareHouseId;
        this.skuCode = skuCode;
    }

    @ThriftField(1)
    public long getWareHouseId() {
        return wareHouseId;
    }

    @ThriftField(2)
    public int getSkuCode() {
        return skuCode;
    }

    @ThriftField
    public void setWareHouseId(long wareHouseId) {
        this.wareHouseId = wareHouseId;
    }

    @ThriftField
    public void setSkuCode(int skuCode) {
        this.skuCode = skuCode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SkuPairKey that = (SkuPairKey) o;
        return wareHouseId == that.wareHouseId && skuCode == that.skuCode;
    }

    @Override
    public int hashCode() {

        return Objects.hash(wareHouseId, skuCode);
    }

}

**Comment by ethe** [comment]
Which you post above is a Java code, Python does not know how to hash this.

**Comment by taomin1** [comment]
> Which you post above is a Java code, Python does not know how to hash this.

But when thrift client is java, It can hash this.
So, How do i deal with it.

**Comment by ethe** [comment]
Use a Python hashable type.

**Comment by taomin1** [comment]
in the thriftpy2.protocol.binary.py line280
k_val = read_val(inbuf, k_type, k_spec, decode_response)
v_val = read_val(inbuf, v_type, v_spec, decode_response)
result[k_val] = v_val

The k_val type is read_val from service, how can i use a Python hashbale type

**Comment by ethe** [comment]
Maybe you could consider using `string` or any other common type instead of `SkuPairKey` in you IDL file.

**Comment by taomin1** [comment]
When I add a hashmethod for k_val object,it can work

like:
In the thriftpy2.protocol.binary.py line280
k_val = read_val(inbuf, k_type, k_spec, decode_response)
v_val = read_val(inbuf, v_type, v_spec, decode_response)
setattr(k_val.__class__, "__hash__", object.__hash__)
result[k_val] = v_val

So, I think it is bug, need to fix
