### ISSUE TITLE
No protocol version header 

### ISSUE THREAD

**Issue by naah69** [Thriftpy/thriftpy2#15]
when i use java client to invok my python server,it errors

```
2018-11-02 21:37:01 ERROR    thriftpy.server  - No protocol version header
Traceback (most recent call last):
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/thriftpy/server.py", line 95, in handle
    self.processor.process(iprot, oprot)
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/thriftpy/thrift.py", line 294, in process
    api, seqid, result, call = self.process_in(iprot)
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/thriftpy/thrift.py", line 250, in process_in
    api, type, seqid = iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 439, in cybin.TCyBinaryProtocol.read_message_begin
cybin.ProtocolError: No protocol version header
```

**Comment by ethe** [comment]
Thriftpy TBinaryProtocol needs protocol version in message, see https://github.com/apache/thrift/blob/master/doc/specs/thrift-binary-protocol.md#message

**Comment by naah69** [comment]
i find the cause.
it is my java client use NIO,but my python use BIO

**Comment by naah69** [comment]
how to user NIO in thriftpy2

**Comment by ethe** [comment]
It is an issue about protocol layer,  is not relevant to the transport.

**Comment by naah69** [comment]
i find the problem.the cause is that py use unframed transport，and java use framed transport.
thanks for your answer.
the last,i still have a question to consult you.
how to set transport?

**Comment by ethe** [comment]
`make_server(pingpong_thrift.PingPong, Dispatcher(), '127.0.0.1', 6000, trans_factory=TFramedTransportFactory())`

**Comment by naah69** [comment]
thank you ,i had resolved my problem.
