### ISSUE TITLE
How can I convert a dict object(with Map Type) to a thrift object?

### ISSUE THREAD

**Issue by liuweiming1997** [Thriftpy/thriftpy2#152]
HI guys.
I am facing a bug that can`t parse python dict to the thrift object. Here is the simple.
Can anyone help me? Thanks a lot.

**enum.thrift**
```
namespace c_glib base
namespace cpp base
namespace py base
namespace go base
namespace java base
namespace js base

enum Status {
	SUCCESS = 1,
	FAIL = 2,
}

struct Children {
  1: optional string name,
}

struct Person {
  1: optional string id,
  2: optional string url,
  3: optional string appid,
  4: optional i64 submit_time,
  5: optional Status person_status,
  6: optional Children children,

  10: optional map<string, string> params,
}

service post_data {
  Status do_post(1: Person person)
}
```

**main.py**
```
import thriftpy2

from thriftpy2.rpc import client_context
import thriftpy2.protocol.json as thrift_json_tool

enum_thrift = thriftpy2.load("enum.thrift", module_name="enum_thrift")

person = enum_thrift.Person()

person_dict = {
    'id': '1',
    'url': 'http://www.google.com',
    # this filed can not parse
    'params': {
        'xxx': 'bbb',
        'yyy': 'ccc',
    }
}

thrift_json_tool.struct_to_obj(val=person_dict, obj=person)

print(person)
```

**Error:**
```
Traceback (most recent call last):
  File "thrift_py2_use.py", line 20, in <module>
    thrift_json_tool.struct_to_obj(val=person_dict, obj=person)
  File "/home/weimingliu/.local/lib/python3.5/site-packages/thriftpy2/protocol/json.py", line 149, in struct_to_obj
    obj_value(field_type, val[field_name], field_type_spec))
  File "/home/weimingliu/.local/lib/python3.5/site-packages/thriftpy2/protocol/json.py", line 59, in obj_value
    return func(*args)
  File "/home/weimingliu/.local/lib/python3.5/site-packages/thriftpy2/protocol/json.py", line 75, in map_to_obj
    value_type, v["value"], value_spec)
TypeError: string indices must be integers
```

**Comment by liuweiming1997** [comment]
DO we need this format?

**Comment by JonnoFTW** [comment]
That particular function is intended to convert `dict`s in the thriftpy2 json format into thrift objects. If you have a simple dict and want to make it into a thrift object. You can always do:

    person = enum_thrift.Person(**person_dict)

This only works for simple thrift structs (ie. ones that aren't nested). Otherwise you'll have to write something recursive that reads the thrift spec.

**Comment by ms300** [comment]
@JonnoFTW I have the save issue and thanks for the `dict_to_thrift ` function.
And there is a little problem in the code.
```
        # handle each type here
        if thrift_type in (TType.LIST, TType.SET):
            result[field_name] = [dict_to_thrift(spec[2], x, ignore_missing) for x in dict_data]
        if thrift_type == TType.STRUCT:
            result[field_name] = dict_to_thrift(spec[2], dict_data, ignore_missing)
        if thrift_type == TType.MAP:
            result[field_name] = {
                dict_to_thrift(spec[2][0], k, ignore_missing):
                    dict_to_thrift(spec[2][1], v, ignore_missing) for k, v in
                dict_data.items()}
        else:
            result[field_name] = dict_data
```

should be 
```
        # handle each type here
        if thrift_type in (TType.LIST, TType.SET):
            result[field_name] = [dict_to_thrift(spec[2], x, ignore_missing) for x in dict_data]
        elif thrift_type == TType.STRUCT:
            result[field_name] = dict_to_thrift(spec[2], dict_data, ignore_missing)
        elif thrift_type == TType.MAP:
            result[field_name] = {
                dict_to_thrift(spec[2][0], k, ignore_missing):
                    dict_to_thrift(spec[2][1], v, ignore_missing) for k, v in
                dict_data.items()}
        else:
            result[field_name] = dict_data
```

**Comment by JonnoFTW** [comment]
@ms300 thanks, I've updated my code

**Comment by liuweiming1997** [comment]
Thanks  all guy`s useful code.
I suggest this function can maintain by the repos.

**Comment by JonnoFTW** [comment]
@liuweiming1997 please keep in mind that thriftpy2 doesn't currently support optional fields since this information is excluded from the `thrift_spec` attribute of thrift objects.

**Comment by chzhc** [comment]
another approach may serialize and then deserialize json into thrift obj. ugly but works.
```python
import json
from thriftpy2.utils import deserialize
from thriftpy2.protocol import TJSONProtocolFactory

def json_to_thrift(thrift_object, payload):
    g = {"payload": json.loads(payload), "metadata": {"version": 1}} 
    ps = json.dumps(g)
    buf = int.to_bytes(len(ps), 4, "big") + str.encode(ps)
    return deserialize(thrift_object, buf, proto_factory=TJSONProtocolFactory())
```
