### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by JackYangzg** [Thriftpy/thriftpy2#73]
windows is raise exception and linux is ok.
when I use rpc client in subprocess [using multiprocess.Process start]
Raise Exception：
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\ProgramData\Anaconda3\lib\site-packages\thriftpy2\thrift.py", line 180, in __getattr__
    print(self._service.thrift_services)
  File "D:\ProgramData\Anaconda3\lib\site-packages\thriftpy2\thrift.py", line 180, in __getattr__
    print(self._service.thrift_services)
  File "D:\ProgramData\Anaconda3\lib\site-packages\thriftpy2\thrift.py", line 180, in __getattr__
    print(self._service.thrift_services)
  [Previous line repeated 328 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by ethe** [comment]
How can I reproduce it?

**Comment by ethe** [comment]
The print code `print(self._service.thrift_services)` does not in thriftpy source code, please remove it.
