### ISSUE TITLE
thriftpy2.load(path=url) 当通过url的方式获取加载thrift文件时会报错

### ISSUE THREAD

**Issue by taomin1** [Thriftpy/thriftpy2#77]
thriftpy2.load(path=url) 当通过url的方式获取加载thrift文件时会报错
TypeError: 'in <string>' requires string as left operand, not int
因为在thriftpy2.parser.parser文件line 567 data = urlopen(path).read()，data的type是bytes，不是string
当改成data = urlopen(path).read().decode('utf-8')时问题就解决了
请问是否有计划完善这部分？

**Comment by ethe** [comment]
How to reproduce it?

**Comment by taomin1** [comment]
复现步骤：
搭建1个server，返回idl文件，例如http://10.21.59.179:9981/getThriftIdlFile/TCsuGridInfoSearchService.thrift返回的是1个正确的时候idl文件
通过thriftpy2.load(path="http://10.21.59.179:9981/getThriftIdlFile/TCsuGridInfoSearchService.thrift")
会报错，报错信息如下：
Traceback (most recent call last):
  File "/Users/taomin/PycharmProjects/b2b_api_case_core/object/tool/thriftClientFactoryV2.py", line 336, in <module>
    thriftClientFactory2 = thriftClientFactoryV2('ssc','TCsuGridInfoSearchService','com.sankuai.klssc.search','com.sankuai.bb.op.sms')
  File "/Users/taomin/PycharmProjects/b2b_api_case_core/object/tool/thriftClientFactoryV2.py", line 34, in __init__
    self.thriftLoadIDL = thriftpy2.load(path="http://10.21.59.179:9981/getThriftIdlFile/TCsuGridInfoSearchService.thrift")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/parser/__init__.py", line 33, in load
    include_dir=include_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/parser/parser.py", line 585, in parse
    parser.parse(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ply/yacc.py", line 1061, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ply/lex.py", line 314, in token
    if lexdata[lexpos] in lexignore:
TypeError: 'in <string>' requires string as left operand, not int

**Comment by ethe** [comment]
10.21.59.179 is a private network IP, and I can not access it.

**Comment by taomin1** [comment]
You can request this link.
https://raw.githubusercontent.com/taomin1/thriftFile/master/TSalesUnitSearchService.thrift
Steps to reproduce the problem,
thriftpy2.load(path="https://raw.githubusercontent.com/taomin1/thriftFile/master/TSalesUnitSearchService.thrift")

**Comment by ulidtko** [comment]
Well, that's a plain old Python3 unicode vs bytestring issue.

```
$ python3 -c 'print(b"hello"[0] in "abcdeh")'
TypeError: 'in <string>' requires string as left operand, not int
```

And it happens inside `ply` guts, deep in the lexer.

`ply` 3.0+ [claims to fully support python3][ply-3]; but I'm somewhat dubious of that claim, looking at its [open issues](https://github.com/dabeaz/ply/issues), [this unmerged PR](https://github.com/dabeaz/ply/pull/147) and some of its code fragments.

[ply-3]: https://github.com/dabeaz/ply#special-note-for-ply-30

Perhaps what they mean by "Python3 is supported" really is "Python3 is supported, *as long as you use it in just the right way*", with undetermined values of *just the right way*.

Hey @cclauss ! Could you take a quick look if this project uses `ply` on Python3 correctly?

**Comment by cclauss** [comment]
Sorry, I do not know.

**Comment by ethe** [comment]
I think https://github.com/Thriftpy/thriftpy2/pull/88 can solve this.
