### ISSUE TITLE
Can't pickle TMemoryBuffer class for Pyspark Spark-Submit

### ISSUE THREAD

**Issue by tinder-davidkawashima** [Thriftpy/thriftpy2#92]
I'm havign trouble pickling TMemoryBuffer so I can use the object within a spark-submit pyspark job. Has anyone seen this before/found a good workaround?

Pickling error:
```
>>> transportIn = TMemoryBuffer(bytes_l)
>>> pickle.dumps(transportIn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib64/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/usr/lib64/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "stringsource", line 2, in thriftpy2.transport.cybase.TCyBuffer.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

Spark-Submit error:
```
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/mnt/yarn/usercache/hadoop/appcache/application_1570742233522_0318/container_1570742233522_0318_01_000003/pyspark.zip/pyspark/worker.py", line 216, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1570742233522_0318/container_1570742233522_0318_01_000003/pyspark.zip/pyspark/worker.py", line 58, in read_command
    command = serializer._read_with_length(file)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1570742233522_0318/container_1570742233522_0318_01_000003/pyspark.zip/pyspark/serializers.py", line 170, in _read_with_length
    return self.loads(obj)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1570742233522_0318/container_1570742233522_0318_01_000003/pyspark.zip/pyspark/serializers.py", line 562, in loads
    return pickle.loads(obj)
ImportError: No module named thriftpy2.transport.memory.cymemory
```

**Comment by ethe** [comment]
I do not well know about pyspark, I think you should ask them for help first. However, I think you should not pickle the TMemoryBuffer object, it does not make sense, transport object only handles the data transporting, it is not data itself.
